name: 'Flutter Melos Setup'
description: 'Sets up Flutter, Dart, and Melos for a monorepo'

inputs:
  flutter-channel:
    description: 'Flutter channel to use'
    required: false
    default: 'stable'
  java-version:
    description: 'Java version to use'
    required: false
    default: '17'
  setup-java:
    description: 'Whether to setup Java'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - uses: subosito/flutter-action@v2
      with:
        channel: ${{ inputs.flutter-channel }}
        cache: true
        
    - if: inputs.setup-java == 'true'
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: ${{ inputs.java-version }}
        
    - name: Install Melos
      shell: bash
      run: dart pub global activate melos
      
    - name: Setup Melos
      shell: bash
      run: melos bootstrap