targets:
  $default:
    builders:
      riverpod_generator:
        enabled: true
        generate_for:
          - "**/providers/**.dart"
          - "**/data/**.dart"
      freezed:
        enabled: true
        generate_for:
          - "**/models/**.dart"
          - "**/entities/**.dart"
      json_serializable:
        enabled: true
        generate_for:
          - "**/models/**.dart"
          - "**/entities/**.dart"
        options:
          explicit_to_json: true
          include_if_null: false