name: app_zugantor
description: "Main Zugantor Flutter application"
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  zugantor_core:
    path: ../../packages/zugantor_core
  cupertino_icons: ^1.0.2
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.9
  firebase_storage: ^11.6.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true