name: feature_theme
description: "Shared theming module for Zugantor apps"
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  zugantor_core:
    path: ../../packages/zugantor_core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1