name: feature_auth
description: "Authentication feature module for Zugantor apps"
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  zugantor_core:
    path: ../../packages/zugantor_core
  # Dependency injection
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  # For secure storage
  flutter_secure_storage: ^9.0.0
  # For data classes
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  freezed: ^2.4.6
  json_serializable: ^6.7.1