name: zugantor_core
description: "Core utilities and shared functionality for Zugantor applications"
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Dependency injection and state management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  # HTTP client for network requests
  dio: ^5.4.0
  # Code generation
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  # Code generation
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  custom_lint: ^0.5.7
  riverpod_lint: ^2.3.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1