name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  analyze:
    name: Static Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4
      
      - uses: ./.github/actions/setup
        with:
          flutter-channel: 'stable'

      - name: Verify formatting
        run: melos run format

      - name: Analyze project
        run: melos run analyze

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4
      
      - uses: ./.github/actions/setup
        with:
          flutter-channel: 'stable'

      - uses: ./.github/actions/test-coverage
        with:
          coverage-token: ${{ secrets.CODECOV_TOKEN }}
          coverage-flags: 'unit,integration'