name: Deploy to Staging

on:
  push:
    branches:
      - 'develop'
      - 'staging'

jobs:
  setup-environment:
    name: Setup Environment
    runs-on: ubuntu-latest
    outputs:
      env_name: ${{ steps.set-env.outputs.env_name }}
    steps:
      - id: set-env
        run: |
          if [ ${{ github.ref }} = "refs/heads/develop" ]; then
            echo "env_name=dev" >> $GITHUB_OUTPUT
          else
            echo "env_name=staging" >> $GITHUB_OUTPUT
          fi

  deploy-android:
    name: Deploy Android to Firebase
    needs: setup-environment
    runs-on: ubuntu-latest
    timeout-minutes: 45
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: ./.github/actions/setup
        with:
          flutter-channel: 'stable'
          setup-java: 'true'
          java-version: '17'
      
      - uses: ./.github/actions/deploy-setup
        with:
          environment: ${{ needs.setup-environment.outputs.env_name }}
          platform: 'android'
          build-number: ${{ github.run_number }}

      - uses: ./.github/actions/app-build
        with:
          platform: 'android'
          build-type: 'release'
          target-directory: 'apps/app_zugantor'
          environment: ${{ needs.setup-environment.outputs.env_name }}
      
      - name: Upload to Firebase
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: testers
          file: apps/app_zugantor/build/artifacts/app-release.apk
          releaseNotes: |
            Branch: ${{ github.ref }}
            Environment: ${{ needs.setup-environment.outputs.env_name }}
            Build: ${{ github.run_number }}

  deploy-ios:
    name: Deploy iOS to TestFlight
    needs: setup-environment
    runs-on: macos-latest
    timeout-minutes: 45
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: ./.github/actions/setup
        with:
          flutter-channel: 'stable'
      
      - uses: ./.github/actions/deploy-setup
        with:
          environment: ${{ needs.setup-environment.outputs.env_name }}
          platform: 'ios'
          build-number: ${{ github.run_number }}

      - uses: ./.github/actions/ios-setup
        with:
          p12-certificate: ${{ secrets.IOS_P12_CERTIFICATE }}
          p12-password: ${{ secrets.IOS_P12_PASSWORD }}
          bundle-id: "com.zugantor.*"
          appstore-issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          appstore-key-id: ${{ secrets.APPSTORE_KEY_ID }}
          appstore-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}

      - uses: ./.github/actions/app-build
        with:
          platform: 'ios'
          build-type: 'release'
          target-directory: 'apps/app_zugantor'
          environment: ${{ needs.setup-environment.outputs.env_name }}

      - name: Upload to TestFlight
        env:
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
        run: |
          xcrun altool --upload-app \
            -f "apps/app_zugantor/build/artifacts/app_zugantor.app" \
            -t ios \
            -u "${{ secrets.APPLE_ID }}" \
            -p "${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}"