name: Release Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build-android:
    name: Build Android Apps
    runs-on: ubuntu-latest
    timeout-minutes: 60
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: ./.github/actions/setup
        with:
          flutter-channel: 'stable'
          setup-java: 'true'
          java-version: '17'
      
      - uses: ./.github/actions/build-prep
        with:
          environment: 'prod'
          keystore-base64: ${{ secrets.KEYSTORE_BASE64 }}
          store-password: ${{ secrets.STORE_PASSWORD }}
          key-password: ${{ secrets.KEY_PASSWORD }}
          key-alias: ${{ secrets.KEY_ALIAS }}

      - uses: ./.github/actions/app-build
        with:
          platform: 'android'
          build-type: 'release'
          target-directory: 'apps/app_zugantor'
          environment: 'prod'

      - uses: ./.github/actions/app-build
        with:
          platform: 'android'
          build-type: 'release'
          target-directory: 'apps/app_admin'
          environment: 'prod'

      - name: Upload Android Builds
        uses: actions/upload-artifact@v4
        with:
          name: android-releases
          path: |
            apps/*/build/artifacts/*.apk

  build-ios:
    name: Build iOS Apps
    runs-on: macos-latest
    timeout-minutes: 60
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: ./.github/actions/setup
        with:
          flutter-channel: 'stable'
      
      - uses: ./.github/actions/ios-setup
        with:
          p12-certificate: ${{ secrets.IOS_P12_CERTIFICATE }}
          p12-password: ${{ secrets.IOS_P12_PASSWORD }}
          bundle-id: "com.zugantor.*"
          appstore-issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          appstore-key-id: ${{ secrets.APPSTORE_KEY_ID }}
          appstore-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}

      - uses: ./.github/actions/app-build
        with:
          platform: 'ios'
          build-type: 'release'
          target-directory: 'apps/app_zugantor'
          environment: 'prod'
          extra-args: '--no-codesign'

      - uses: ./.github/actions/app-build
        with:
          platform: 'ios'
          build-type: 'release'
          target-directory: 'apps/app_admin'
          environment: 'prod'
          extra-args: '--no-codesign'

      - name: Upload iOS Builds
        uses: actions/upload-artifact@v4
        with:
          name: ios-releases
          path: |
            apps/*/build/artifacts/*.app

  create-release:
    name: Create Release
    needs: [build-android, build-ios]
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            android-releases/*
            ios-releases/*
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}