name: Security and Dependencies Check

on:
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sunday
  workflow_dispatch:  # Allow manual trigger
  push:
    paths:
      - '**/pubspec.yaml'
      - '**/pubspec.lock'

jobs:
  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v3
        with:
          fail-on-severity: moderate
          
  outdated-dependencies:
    name: Check Outdated Dependencies
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
          
      - name: Install Melos
        run: dart pub global activate melos
        
      - name: Check outdated packages
        run: |
          melos exec -- "flutter pub outdated"
          
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Run Horusec Security Scan
        uses: facebookincubator/horusec-action@v0.2.2
        with:
          arguments: -p="./" -e="true"
          
      - name: Run OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'zugantor'
          path: '.'
          format: 'HTML'
          
      - name: Upload Security Report
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            horusec-report.json
            dependency-check-report.html